#!/usr/bin/python

"""
Cobbler external inventory script
=================================

Ansible has a feature where instead of reading from /etc/ansible/hosts
as a text file, it can query external programs to obtain the list
of hosts, groups the hosts are in, and even variables to assign to each host.  

To use this, copy this file over /etc/ansible/hosts and chmod +x the file.
This, more or less, allows you to keep one central database containing
info about all of your managed instances.

This script is an example of sourcing that data from Cobbler
(http://cobbler.github.com).  With cobbler each --mgmt-class in cobbler 
will correspond to a group in Ansible, and --ks-meta variables will be 
passed down for use in templates or even in argument lines.

See http://ansible.github.com/api.html for more info
"""

# (c) 2012, Michael DeHaan <michael.dehaan@gmail.com>
#
# This file is part of Ansible,
#
# Ansible is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.

######################################################################

import sys
import xmlrpclib
import shlex

from cobbler import utils

try:
    import json
except:
    import simplejson as json

# NOTE -- this file assumes Ansible is being accessed FROM the cobbler
# server, so it does not attempt to login with a username and password.
# this will be addressed in a future version of this script.

conn = xmlrpclib.Server(utils.local_get_cobbler_api_url(), allow_none=True)

###################################################
# executed with no parameters, return the list of
# all groups and hosts

if sys.argv[1] == '--list':

    systems = conn.get_item_names('system')
    groups = { 'ungrouped' : [] }

    for system in systems:
        data = conn.get_blended_data(None, system)

        # Use the default hostname set for the host
        dns_name = data["hostname"]

        interfaces = data['interfaces']
        for (iname, ivalue) in interfaces.iteritems():
            if ivalue.get('management', False):
                this_dns_name = ivalue.get("dns_name", "").strip()
                if not this_dns_name:
                    this_dns_name = ivalue.get("ip_address","").strip()
                if this_dns_name:
                    dns_name = this_dns_name
 
        classes  = data['mgmt_classes']
        for cls in classes:
            if cls not in groups:
                groups[cls] = []
            # hostname is not really what we want to insert, really insert the
            # first DNS name but no further DNS names
            if dns_name and dns_name not in groups[cls]:
                groups[cls].append(dns_name)
        else:
            if dns_name and dns_name not in groups['ungrouped']:
                groups['ungrouped'].append(dns_name)
 
    print json.dumps(groups)
    sys.exit(0)

#####################################################
# executed with a hostname as a parameter, return the
# variables for that host

elif sys.argv[1] == '--host':

    # look up the system record for the given DNS name
    data = conn.find_system_by_dns_name(sys.argv[2])
    if not data:
        print json.dumps({})
        sys.exit(1)

    # return the ksmeta data for that system
    metadata = data['ks_meta']
    tokens = shlex.split(metadata)
    results = {}
    for t in tokens:
        if t.find("=") != -1:
           (k,v) = t.split("=",1)
           results[k]=v
    print json.dumps(results)
    sys.exit(0)

